title: "Shreya Vontela"
description: "Principal Data Scientist · ML Modeling · GenAI · Agentic AI"
url: "https://shreyav29.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Site-wide UI
minimal_mistakes_skin: "sunrise"   # try: air, contrast, dark, mint, neon, sunrise
locale: "en-US"

# Build options
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Navigation (top menu)
navigation:
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Contact"
    url: /contact/
  - title: "Resume"
    url: /resume/

# Author card (shows on About and optionally homepage)
author:
  name: "Shreya Vontela"
  avatar: "/assets/avatar.png"   # add this image
  bio: "Principal Data Scientist building ML, GenAI & Agentic AI systems"
  location: "Seattle, WA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/shreyav29"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/shreya-vontela/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "shreyavontelaberkeley@gmail.com"

# Collections (optional blog later)
collections:
  pages:
    output: true
